# Generated by Django 4.2.6 on 2023-11-21 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0003_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='endpoint.product'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('orders', models.ManyToManyField(to='endpoint.order')),
            ],
        ),
    ]
